#INFO: This file generates the GitHub Actions matrix.
include:
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_max_left
    snippet: studio-rpc-usb-uart

  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_max_right
    
  - board: nice_nano
    shield: cradio_left
    artifact-name: ferris_left
    snippet: studio-rpc-usb-uart

  - board: nice_nano
    shield: cradio_right
    artifact-name: ferris_right

