#INFO: This file generates the GitHub Actions matrix.
include:
  #INFO: Bluetooth Corne Max 
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_max_left_zmk_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n

  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_max_right
    
  # #INFO: Bluetooth Ferris Sweep 
  - board: nice_nano
    shield: cradio_left
    artifact-name: ferris_left_zmk_studio 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n 

  - board: nice_nano
    shield: cradio_right
    artifact-name: ferris_right

