#INFO: This file generates the GitHub Actions matrix.
include:
  #INFO: Bluetooth Corne Max 
  - board: nice_nano
    shield: corne_left nice_view_adapter nice_view
    keymap-name: corne_max
    artifact-name: corne_max_left_zmk_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DKEYMAP_NAME=corne_max -DCONF_FILE=config/corne_max.conf

  - board: nice_nano
    shield: corne_right nice_view_adapter nice_view
    keymap-name: corne_max
    artifact-name: corne_max_right
    cmake-args: -DKEYMAP_NAME=corne_max -DCONF_FILE=config/corne_max.conf

  # #INFO: Bluetooth Corne Min
  # - board: corne_min_left
  #   shield: rgbled_adapter
  #   keymap-name: corne_min
  #   artifact-name: corne_min_left_zmk_studio
  #   snippet: studio-rpc-usb-uart
  #   cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y -DKEYMAP_NAME=corne_min -DCONF_FILE=config/corne_min.conf
  #
  # - board: corne_min_right
  #   shield: rgbled_adapter
  #   keymap-name: corne_min
  #   artifact-name: corne_min_right
  #   cmake-args: -DCONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y -DKEYMAP_NAME=corne_min -DCONF_FILE=config/corne_min.conf
    
  # #INFO: Bluetooth Ferris Sweep 
  - board: nice_nano
    shield: cradio_left
    keymap-name: ferris
    artifact-name: ferris_left_zmk_studio 
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n -DKEYMAP_NAME=ferris -DCONF_FILE=config/ferris.conf

  - board: nice_nano
    shield: cradio_right
    keymap-name: ferris
    artifact-name: ferris_right
    cmake-args: -DKEYMAP_NAME=ferris -DCONF_FILE=config/ferris.conf

